version: "3"

services:
  seq:
    image: datalust/seq:2023.3
    volumes:
      - seq-data:/data
    env_file:
      - seq-2023.3/service.env
      - ../.env/seq-2023.3.env
    ports:
      - 5340:80
      - 5341:5341
    networks:
      - devsvcnet

volumes:
  seq-data:
    driver: local
